import config
import logHandler

from .constants import (
	HOTKEY_FORMAT_ABBREVIATED_NO_PLUS,
	HOTKEY_FORMAT_EXPANDED_NO_PLUS,
	HOTKEY_FORMAT_NATIVE,
	HOTKEY_MODE_BOTH,
	HOTKEY_MODE_CHOICES,
	HOTKEY_MODE_DIALOGS,
	HOTKEY_MODE_MENUS,
	HOTKEY_MODE_OFF,
	HOTKEY_TYPES_ACCESS,
	HOTKEY_TYPES_BOTH,
	HOTKEY_TYPES_COMMAND,
	PAUSE_MODE_GLOBAL,
	PAUSE_PLACEMENT_BEFORE,
	POSITION_MODE_EACH,
	POSITION_MODE_FIRST,
	POSITION_MODE_OFF,
	QUERY_OBJECT_SOURCE_FOCUS,
	QUERY_OBJECT_SOURCE_NATIVE,
	QUERY_OBJECT_SOURCE_NAVIGATOR,
	TOKEN_ORDER_KINDS,
	TOKEN_PAUSE_USE_GLOBAL,
)

log = logHandler.log

from .config_core import (
	_ensure_classic_speech_section,
	_get_live_verbosity_manager,
	_get_nvda_setting,
	_get_running_classic_speech_plugin,
	_replace_section_contents,
	_set_nvda_setting,
	_to_plain_data,
)

from .profile_config import (
	_apply_profile_behavior_runtime,
	_apply_profile_live,
	_apply_profile_live_if_active,
	_clear_profile_behavior_override,
	_clear_profile_override,
	_clone_profile_from_manager,
	_default_profile_behavior,
	_get_active_profile_name,
	_get_profile_behavior,
	_preview_profile_config,
	_save_profile_behavior,
	_save_profile_config,
	_set_active_profile_name,
)

from .menus_config import (
	_get_menu_bar_focus_enabled,
	_get_menu_bar_focus_message,
	_get_menu_bar_leave_enabled,
	_get_menu_bar_leave_message,
	_get_menu_close_enabled,
	_get_menu_close_message,
	_get_menu_open_enabled,
	_get_menu_open_message,
	_set_menu_bar_focus_enabled,
	_set_menu_bar_focus_message,
	_set_menu_bar_leave_enabled,
	_set_menu_bar_leave_message,
	_set_menu_close_enabled,
	_set_menu_close_message,
	_set_menu_open_enabled,
	_set_menu_open_message,
)


from .misc_config import (
	_FALLBACK_SPEECH_DELAY_CHOICES,
	_choice_string_to_fallback_delay,
	_fallback_delay_to_choice_string,
	_get_speech_interrupt_for_enter_enabled,
	_get_speech_interrupt_for_typed_characters_enabled,
	_get_automatic_speech_interrupt_fallback_ms,
	_get_default_button_enabled,
	_get_guess_object_position_information_when_unavailable,
	_get_object_navigation_processing_enabled,
	_get_prevent_automatic_speech_interrupt_enabled,
	_get_query_object_source,
	_set_speech_interrupt_for_enter_enabled,
	_set_speech_interrupt_for_typed_characters_enabled,
	_set_automatic_speech_interrupt_fallback_ms,
	_set_default_button_enabled,
	_set_guess_object_position_information_when_unavailable,
	_set_object_navigation_processing_enabled,
	_set_prevent_automatic_speech_interrupt_enabled,
	_set_query_object_source,
	get_object_navigation_processing_enabled,
	get_query_object_source,
)

from .text.config import (
	LIST_ITEM_STATE_REPORTING_BOTH,
	LIST_ITEM_STATE_REPORTING_MODES,
	LIST_ITEM_STATE_REPORTING_NONE,
	LIST_ITEM_STATE_REPORTING_NOT_SELECTED,
	LIST_ITEM_STATE_REPORTING_SELECTED,
	REPEATED_CHARACTER_MODE_3,
	REPEATED_CHARACTER_MODE_4,
	REPEATED_CHARACTER_MODE_5,
	REPEATED_CHARACTER_MODE_6,
	REPEATED_CHARACTER_MODE_ALL,
	REPEATED_CHARACTER_MODE_COUNT,
	REPEATED_CHARACTER_MODE_NATIVE,
	REPEATED_CHARACTER_MODES,
	SPELL_ALPHANUMERIC_DATA_MODES,
	SPELL_ALPHANUMERIC_DATA_OFF,
	SPELL_ALPHANUMERIC_DATA_SPELL,
	_ensure_text_processing_section,
	_get_announce_new_lines_during_say_all_enabled,
	_get_list_item_state_reporting_mode,
	_get_new_line_message,
	_get_repeated_character_filter_enabled,
	_get_repeated_character_limit,
	_get_repeated_character_mode,
	_get_spell_alphanumeric_data_mode,
	_get_split_mixed_case_words_enabled,
	_get_suppress_word_internal_dashes_enabled,
	_set_list_item_state_reporting_mode,
	_set_repeated_character_filter_enabled,
	_set_repeated_character_limit,
	_set_repeated_character_mode,
	_set_announce_new_lines_during_say_all_enabled,
	_set_new_line_message,
	_set_spell_alphanumeric_data_mode,
	_set_split_mixed_case_words_enabled,
	_set_suppress_word_internal_dashes_enabled,
	get_repeated_character_filter_enabled,
	get_repeated_character_mode,
	get_announce_new_lines_during_say_all_enabled,
	get_list_item_state_reporting_mode,
	get_new_line_message,
	get_spell_alphanumeric_data_mode,
	get_split_mixed_case_words_enabled,
	get_suppress_word_internal_dashes_enabled,
)

from .number_processing_config import (
	CURRENCY_PROCESSING_DOLLARS_AND_CENTS,
	CURRENCY_PROCESSING_MODES,
	CURRENCY_PROCESSING_NATIVE,
	NUMBER_PROCESSING_MODE_FULL_NUMBERS,
	NUMBER_PROCESSING_MODE_PAIRS,
	NUMBER_PROCESSING_MODE_SINGLE_DIGITS,
	NUMBER_PROCESSING_MODE_SYNTHESIZER,
	NUMBER_PROCESSING_MODES,
	PHONE_NUMBER_PROCESSING_GROUPED_DIGITS,
	PHONE_NUMBER_PROCESSING_MODES,
	PHONE_NUMBER_PROCESSING_NATIVE,
	NUMERIC_DATE_FORMAT_DMY,
	NUMERIC_DATE_FORMAT_MDY,
	NUMERIC_DATE_FORMAT_YMD,
	NUMERIC_DATE_FORMATS,
	NUMERIC_DATE_PROCESSING_FULL,
	NUMERIC_DATE_PROCESSING_MODES,
	NUMERIC_DATE_PROCESSING_NATIVE,
	NUMERIC_DATE_PROCESSING_SOME,
	SINGLE_DIGITS_THRESHOLD_SYNTHESIZER,
	SINGLE_DIGITS_THRESHOLDS,
	_ensure_number_processing_section,
	_get_currency_processing_mode,
	_get_friendly_toll_free_prefixes_enabled,
	_get_number_processing_mode,
	_get_numeric_date_format,
	_get_numeric_date_processing_mode,
	_get_phone_number_processing_mode,
	_get_recognize_iso_dates_enabled,
	_get_single_digits_threshold,
	_get_use_windows_date_format_enabled,
	_set_currency_processing_mode,
	_set_friendly_toll_free_prefixes_enabled,
	_set_number_processing_mode,
	_set_numeric_date_format,
	_set_numeric_date_processing_mode,
	_set_phone_number_processing_mode,
	_set_recognize_iso_dates_enabled,
	_set_single_digits_threshold,
	_set_use_windows_date_format_enabled,
	get_currency_processing_mode,
	get_friendly_toll_free_prefixes_enabled,
	get_number_processing_mode,
	get_numeric_date_format,
	get_numeric_date_processing_mode,
	get_phone_number_processing_mode,
	get_recognize_iso_dates_enabled,
	get_single_digits_threshold,
	get_use_windows_date_format_enabled,
)

from .advanced_config import (
	_get_announce_speech_hook_loaded_enabled,
	_get_debug_logging_enabled,
	_get_speech_hook_enabled,
	_get_speech_hook_loaded_message,
	_set_announce_speech_hook_loaded_enabled,
	_set_debug_logging_enabled,
	_set_speech_hook_enabled,
	_set_speech_hook_loaded_message,
	get_announce_speech_hook_loaded_enabled,
	get_debug_logging_enabled,
	get_speech_hook_enabled,
	get_speech_hook_loaded_message,
)

from .hotkeys_config import (
	_get_hotkey_dialog_access_key_only,
	_get_hotkey_format,
	_get_hotkey_mode,
	_get_hotkey_mode_label,
	_get_hotkey_types,
	_set_hotkey_dialog_access_key_only,
	_set_hotkey_format,
	_set_hotkey_mode,
	_set_hotkey_types,
)

from .shape_config import (
	_clone_shape_from_manager,
	_preview_shape_config,
	_preview_token_shape_edits,
	_save_shape_config,
	_save_token_shape_edits,
)

from .key_labels_config import (
	_clone_key_label_config,
	_preview_key_label_config,
	_save_key_label_config,
)
